### ISSUE TITLE
README: Install from Github clone

### ISSUE THREAD

**Issue by jimt** [pimoroni/unicorn-hat#103]
The **Install from Github clone** instructions appear to be out of date. The `library/rpi-ws281x` directory no longer exists in the repository.

And on a more minor level, I would suggest changing the header to capitalize it as **GitHub**.

**Comment by Gadgetoid** [comment]
Good spot, the rpi-ws281x library was never really *part* of Unicorn HAT so I've been disentangling the two and haven't updated the docs yet.

Its new home is: https://github.com/pimoroni/rpi_ws281x-python
