### ISSUE TITLE
Use full brightness

### ISSUE THREAD

**Issue by 4goettma** [pimoroni/unicorn-hat#120]
Maximum brightness was changed.
Why was this done and how can I change it back?
~~Which commit/file contains the change?~~
Found the commit: https://github.com/pimoroni/unicorn-hat/commit/4679d4ac61cf16673d6f9f2fde1d7491cc2af634

Would be nice to get some more details to know the risks. Used it in the past on full brightness, unicorn-hat board got quite warm but RasbPi was ~~always stable~~ (almost always, I remember now a few crashes with full brightness and on off flashing - not sure whether caused by unicorn-hat or poor power adapter).

Special command to override the brightness cap would be a nice solution - if you're using very low values to display darker colors, you have to re-adjust everything because of the cap. Just scaling the values modifies the colors (255,255,255 isn't a perfect neutral white for example and so on).

**Comment by Gadgetoid** [comment]
The theoretical maximum current draw of those LEDs at full brightness is 20mA per element, x 3 elements, x 8, x 8. Or around 3.8A. The headroom from a 2.5A Pi power supply is around 1.5A.

The brightness limit is to prevent overheating and instability and potential damage from pulling more current than the Pi is capable of delivering. We've no plans to officially support removing it.
