### ISSUE TITLE
Binary clock date is wrong

### ISSUE THREAD

**Issue by datruck** [pimoroni/unicorn-hat#127]
In the example binary_clock.py the implementation of day is incorrect. How can 31 days be represented by only 4 bits? 5 bits would be needed. However that would interfere with the 4 bits currently used for month. Not sure how this can be fixed.

**Comment by Pyroseza** [comment]
oof how did I not see this issue, thanks for fixing it guys.

I'm actually working on this again doing a rewrite with things I've learnt over the last 2 years
