### ISSUE TITLE
unicornd is not supported on Pi 3B+

### ISSUE THREAD

**Issue by jakane** [pimoroni/unicorn-hat#131]
Unable to start unicornd on a rasberry Pi 3B+

$ grep Revision /proc/cpuinfo 
Revision        : a020d3

Patching up fixes this:

$ diff rpihw.c.bak rpihw.c
297a298,308
>     // // jkane
>     // Pi 3 Model B+
>     //
>     {
>         .hwver  = 0xa020d3,
>         .type = RPI_HWVER_TYPE_PI2,
>         .periph_base = PERIPH_BASE_RPI2,
>         .videocore_base = VIDEOCORE_BASE_RPI2,
>         .desc = "Pi 3",
>     },
>     //

**Comment by Gadgetoid** [comment]
Ah, thanks! Looks like I need to update that submodule to track a newer version of `rpi_ws281x`.
