### ISSUE TITLE
What is the licence of library_c/unicorn and library_c/unicornd?

### ISSUE THREAD

**Issue by jacobbramley** [pimoroni/unicorn-hat#136]
I ask because I'd like to submit a pull request affecting both tools.

There are both MIT and GPLv2 licence files at the repository top level, but it's not clear how these apply. I noticed that library_c/unicornd/unicornd.c has a GPLv2 banner at the top, but this is the only example of this under library_c.

**Comment by Gadgetoid** [comment]
`unicornd` is user-contributed code which I should probably have requested a re-license to MIT on to match with our house licensing.

`unicorn.c`- is licensed MIT and the underlying library `rpi_ws218x` is licensed as BSD 2-Clause, which is more or less MIT.

@jibi - for the sake of consistency, could we please relicense Unicornd as MIT?

**Comment by jibi** [comment]
@Gadgetoid yes, absolutely fine for me to relicense it :+1: (although it looks like there have been other contributors who worked on that)

**Comment by Gadgetoid** [comment]
@jibi thank you! That should make things simpler.
