### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by williamtrennem** [pimoroni/unicorn-hat#15]
I have a speaker connected to my A+. I have set the audio output to the 3.5mm jack. Launching python examples causes sound glitches. Is it normal ?

**Comment by Gadgetoid** [comment]
Yes, unfortunately it's normal. The extremely bonkers process used to create the signal required to drive Unicorn HAT involves using the PWM hardware that's crucial to analog audio, so both can't be used at the same time.

**Comment by williamtrennem** [comment]
That's what I thought. Thank you for confirmation.
