### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by snobu** [pimoroni/unicorn-hat#19]
Chrome
192.168.111.22 - - [27/Feb/2015 00:53:49] "GET /pixel/0/7/132/0/0 HTTP/1.1" 200 -
192.168.111.22 - - [27/Feb/2015 00:53:49] "GET /show HTTP/1.1" 200 -
192.168.111.22 - - [27/Feb/2015 00:53:49] "GET /pixel/1/7/132/0/0 HTTP/1.1" 200 -
192.168.111.22 - - [27/Feb/2015 00:53:49] "GET /show HTTP/1.1" 200 -
192.168.111.22 - - [27/Feb/2015 00:53:49] "GET /pixel/2/7/132/0/0 HTTP/1.1" 200 -
192.168.111.22 - - [27/Feb/2015 00:53:51] "GET /show HTTP/1.1" 200 -

IE11 (Desktop and Windows Phone 8.1)
192.168.111.22 - - [27/Feb/2015 00:54:47] "GET /pixel/0/7/132/0/0 HTTP/1.1" 200 -
192.168.111.22 - - [27/Feb/2015 00:54:48] "GET /pixel/1/7/132/0/0 HTTP/1.1" 200 -
192.168.111.22 - - [27/Feb/2015 00:54:48] "GET /pixel/2/7/132/0/0 HTTP/1.1" 200 -

IE is missing the /show [pun intended? :)]

unicorn-paint.js
---------------------

    function update_pixels(){
        var changed = false;
        $('td').each(function( index, obj ){
                if( $(obj).data('changed') ){
                        $(obj).data('changed',false);
                        changed = true;

                        var x = $(this).index();
                        var y = $(this).parent().index();
                        var col = tinycolor($(obj).css('background-color')).toRgb();

                        var data = [x,y,col.r,col.g,col.b];

                        $.get('/pixel/' + data.join('/'));
                }
        });
        if(changed){
                $.get('/show');
        }

**Comment by Gadgetoid** [comment]
Sorry! I haven't had the time to look into this yet, but it's not forgotten!
