### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by aptanet** [pimoroni/unicorn-hat#30]
Having been playing with the code I've noted that the README.md file in python/unicorn-hat has an error. It states:

unicornhat.set_pixel( x, y, red, blue, green ) - Set a pixel in the buffer to the specified colour

which struck me as an odd way round. Having played with the settings and had trouble getting the colours I wanted I've confirmed that this should be:

unicornhat.set_pixel( x, y, red, green, blue ) - Set a pixel in the buffer to the specified colour

which is what I expected given it uses RGB colour codes :)

**Comment by Gadgetoid** [comment]
Thanks! Fixed in 6c1d2d69d136ed35952b59f74e3ac011627510a2
