### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by cymplecy** [pimoroni/unicorn-hat#34]
I'm getting
bash: line 13: [: ==: unary operator expected
when running the main curl installer

It seems to carry on OK but it'd be off -putting for newcommers

**Comment by Gadgetoid** [comment]
So there is! I'll have a look into it. Thanks.

**Comment by Gadgetoid** [comment]
Fixed: https://github.com/pimoroni/get/commit/8484a3cb87ea704bd3e2b0603bedc22932702188
