### ISSUE TITLE
rpi-ws281x broken on the latest ArchLinux

### ISSUE THREAD

**Issue by jibi** [pimoroni/unicorn-hat#35]
With the latest ArchLinux release, running on an A+, unicornd is not working.
After digging a bit with gdb I found that the library stucks here

``` c
    while (!(cm_pwm->ctl & CM_PWM_CTL_BUSY))
```

which is at `python/rpi-ws281x/lib/ws2811.c:261`.

**Comment by bendo** [comment]
Last five commits should fix issue with ArchLinux and GCC >= 5.1.0
Sorry, that is not a one fix commit, but I made it in hurry direct on github.

**Comment by mil** [comment]
Any word on this or the related PR @bendo? 
What needs to be done to run `unicornd` on Arch linux ARM? 

On your fork I can get `c/unicorn/unicorn.c` compiled and working but `unicornd` and the python test scripts don't work for me -- `unicornd` occasionally'll throw `DMA error` codes.

**Comment by bendo** [comment]
@mil Back then, I made a quick fix. I can look at `unicornd` and python test scripts, but probably on weekend. No time these days.

**Comment by mil** [comment]
@bendo can't wait -- most thanks for your help

**Comment by Gadgetoid** [comment]
I'm labeling this as such so this issue is open for future Arch users, but not on my "radar" so to speak.

A PR which fixes Arch compatibility without breaking Raspbian, which is my primary concern, would be very welcome. I really don't have the time to work on it myself :(

**Comment by Gadgetoid** [comment]
What's the current state of building on Arch? It might be worth submitting a patch upstream, since that's where I inherit the rpi_ws281x code from, and I plan to completely remove rpi_ws281x from this repository as soon as possible, to rely on the original version.

https://github.com/jgarff/rpi_ws281x

**Comment by bendo** [comment]
@Gadgetoid I think my fork should work fine. To switch rpi_ws281x to original version is good idea. I wanted to do it as well in my fork, but there is no time... Two little kids. :-) You can do changes which you want, and when you will be ready I can try it on Arch. If there will be needed some correction, I will send you pull request.

**Comment by matthewbullweb** [comment]
I can't seem to install this either. This is the last error message I get.

**Comment by Gadgetoid** [comment]
As mentioned above, but with some progress now, I plan to switch over to https://github.com/pimoroni/rpi_ws281x-python soon, which includes the library directly from the upstream dev branch (with PCM and SPI support for driving LEDs) which can be found here: https://github.com/richardghirst/rpi_ws281x
