### ISSUE TITLE
release tag

### ISSUE THREAD

**Issue by ScrumpyJack** [pimoroni/unicorn-hat#49]
would you mind awfully tagging a release. it helps for package building? - thanks

https://help.github.com/categories/releases/

**Comment by Gadgetoid** [comment]
Surprisingly- I've promised myself to get into the habit of tagging at least. I would love to try and retrospectively tag earlier versions too, too, but that could be tricky!

https://github.com/pimoroni/unicorn-hat/tree/v2.0.7

I may be crazy, but I've never been able to find the "Releases" tab or any way to turn it on in GitHub. It would be nice to set up releases and add the pip packages.
