### ISSUE TITLE
paint screen doesn't match output on hat

### ISSUE THREAD

**Issue by vitriolix** [pimoroni/unicorn-hat#60]
Seems like there is some soft of off-by-one type error, sometimes it won't show a pixel i click, no matter how many times i click.  seems like it sometimes shows one off row/column:

https://goo.gl/photos/g1A2YphohfiGTKAEA

https://goo.gl/photos/7aRewjV59GkJpjbb9

**Comment by Gadgetoid** [comment]
This is curious. Has this problem persisted, since I've not seen it before in Unicorn Paint?
