### ISSUE TITLE
Is it normal ?

### ISSUE THREAD

**Issue by francoismartin** [pimoroni/unicorn-hat#85]
Hi,

I bought unicorn phat and I installed in my raspi 2.

When I launch simple.py. I have already 3 leds lighted 

![img_20160912_174738](https://cloud.githubusercontent.com/assets/20554135/18442526/6de2df80-7911-11e6-8a5e-eaa663989d05.jpg)

Normally the code show all led, no ?

And when I write :

```
unicorn.set_layout(unicorn.PHAT)
unicorn.brightness(0.8)
unicorn.rotation(0)

unicorn.set_pixel(0, 0, 255, 0, 0)

unicorn.show()
```

I have 

![img_20160912_174848](https://cloud.githubusercontent.com/assets/20554135/18442535/73b6167a-7911-11e6-9387-101fd473fad2.jpg)

We are oki, it's not normal ?

Thanks

**Comment by Pyroseza** [comment]
Do you similar behaviour when you run the examples?

Kind Regards,
Jarrod Price

--------

**Comment by francoismartin** [comment]
When I runed `rainbow_blink` I had nothing

This video is when I runed `drop.py`

![vid_20160912_183724](https://cloud.githubusercontent.com/assets/20554135/18444197/8d4e5b90-7918-11e6-92ad-66e06aff0dcb.gif)

**Comment by RogueM** [comment]
Have you run the one-line installe? This will ensure that the audio does not interfere with the PWM signal sent to GPIO18 to control the Unicorn.

**Comment by Pyroseza** [comment]
Here is the one liner:

curl -sS get.pimoroni.com/unicornhat | bash

**Comment by francoismartin** [comment]
@RogueM and @Pyroseza 

Thanks.
The first time I had installed with the one liner but It wasn't work but now. It work.

Thank you very much.
