### ISSUE TITLE
LEDs don't show as expected

### ISSUE THREAD

**Issue by mitchhh22** [pimoroni/unicorn-hat#91]
I'm seeing an issue on my unicorn pHAT on my pizero running the latest raspbian jessie where the LEDs aren't triggering correctly...

using the set_pixel function doesn't work consistently and doesn't seem to line up properly even when the layout is set correctly.

The rainbow.py in the example/phat directory doesn't run correctly either. It flashes in random order as if something is wrong.

**Comment by RogueM** [comment]
please run `https://get.pimoroni.com/audio | bash`

...alternatively uncomment `hdmi_force_hotplug=1` in /boot/config.txt

**Comment by mitchhh22** [comment]
That fixed the issue. Thanks!
