### ISSUE TITLE
overloaded methods for colour tuples

### ISSUE THREAD

**Issue by PJOttCanHome** [pimoroni/unicorn-hat#94]
I wrote some code for the Sense Hat that would be nice to port over.  Could you create overloaded methods that allow for colour tuples like was done for the sense hat (and allow clear() to accept (r,g,b) even though set_all() does.  Using a colour tuple is often preferable.
Thanks

**Comment by Gadgetoid** [comment]
I've added support for this into the dev branch which I'm currently working on, if you could install it manually and give it a go I'd appreciate feedback!

https://github.com/pimoroni/unicorn-hat/tree/dev

**Comment by PJOttCanHome** [comment]
Thanks, but it’ll take me a while to test it.  Somehow my Unicornhat just got hosed 2 days ago and so I ordered a new one yesterday.
